---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  include_vars: "../vars/main.yml"
  tags: swap

- name: include release specific variables
  include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
  ignore_errors: true
  tags: swap

- name: include release specific tasks
  include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
  ignore_errors: true
  tags: swap

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/etc/sysctl.d" }
  tags: swap

- name: create swap file if not exists
  command: fallocate -l {{ swap_size }} {{ swap_file }}
  args:
    creates: "{{ swap_file }}"
  register: result
  changed_when: result is not succeeded
  tags: swap

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "{{ swap_file }}", mode: "0600" }
  tags: swap

- name: format swap file
  command: mkswap {{ swap_file }}
  register: result
  changed_when: result is not succeeded
  ignore_errors: true
  tags: swap

- name: mount swap with /etc/fstab
  mount:
    src: "{{ swap_file }}"
    path: none
    fstype: "swap"
    opts: "sw"
    state: "present"
  tags: swap

- name: tweak sysctl entries
  lineinfile:
    path: "/etc/sysctl.d/50-swap.conf"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp | default('^' + item.line | regex_escape() + '$') }}"
    state: "{{ item.state | default('present') }}"
    insertafter: "EOF"
    create: true
  loop: "{{ swap_sysctl }}"
  notify:
    - swap | sysctl --system
  tags: swap

- name: flush handlers
  meta: flush_handlers
  tags: swap
